name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and Push API Gateway Image
        uses: docker/build-push-action@v4
        with:
          context: ./api_gateway
          file: ./api_gateway/Dockerfile
          push: true
          tags: ajilpramod/api_gateway:latest

      - name: Build and Push User Service Image
        uses: docker/build-push-action@v4
        with:
          context: ./user_service
          file: ./user_service/Dockerfile
          push: true
          tags: ajilpramod/user_service:latest

      - name: Build and Push Quiz Service Image
        uses: docker/build-push-action@v4
        with:
          context: ./quiz_service
          file: ./quiz_service/Dockerfile
          push: true
          tags: ajilpramod/quiz_service:latest
